### ISSUE TITLE
Slashing Parameter

### ISSUE THREAD

**Issue by stevenoruzi** [atomone-hub/govgen-genesis#2]
From my perspective, there's an oddity. In GovGen, both the inflation rate and rewards rate are zero, but the slashing parameter isn't zero. This implies that any penalty against a validator will result in a portion of the tokens being permanently removed/burned, leading to a decrease in the total token supply. This scenario seems problematic to me. While I might be mistaken, I wanted to raise this issue to ensure it doesn't negatively impact our governance system.

**Comment by stevenoruzi** [comment]
@giunatale @jaekwon  have you seen my comment by any chance?

**Comment by giunatale** [comment]
I don't see it as problematic. It's ok for the supply to decrease as infractions occur. I don't see it as a problem. Remember that the $GOVGEN token will not be transferrable and won't have any value, plus it won't have anything do to with the final AtomOne distribution, rather voters on GovGen will use their voting power there to deliberate on the AtomOne distribution.

Hope this clarifies, and to reiterate, I don't see it as a problem at all, and it's actually intended.

**Comment by giunatale** [comment]
I will close this @stevenoruzi. But please feel free to comment further or ask more questions!
And thanks for being an active participant!
